language: android
sudo: false
jdk: openjdk7
android:
  components:
    - tools
    - build-tools-23.0.1
    - build-tools-23.0.2
    - extra-android-support
    - extra-android-m2repository
    - android-23
    - sys-img-armeabi-v7a-android-23
  licenses:
    - '.+'


before_script:

script:
  - ./gradlew clean assemble check